business:
  business-switch:
    user:
      user-simple: true
      need-phone: true
    login:
      sms-phone: true
      wechat-applet: true
      email: true
      username: true
    register:
      sms-phone: true
      wechat-applet: true
      username: true
