wechat:
  app-id: ${WECHAT_APPID}
  mini-app:
    app-id: ${wechat.app-id}
    secret: ${WECHAT_SECRET}
    token:
    aes-key:
    msg-data-format: JSON
  pay:
    app-id: ${wechat.app-id}
    mch-id: ${WECHAT_MCH_ID}
    mch-key: ${WECHAT_MCH_KEY}
    sub-app-id:
    sub-mch-id:
    notify-url: ${WECHAT_NOTIFY_URL}
    pay-notify-path: /notify/wechat/payment
    refund-notify-path: /notify/wechat/refund
    api-v3-key: ${WECHAT_API_V3_KEY}
    private-key-path: classpath:cert/apiclient_key.pem
    private-cert-path: classpath:cert/apiclient_cert.pem
    key-path: classpath:cert/apiclient_cert.p12
